# Generated by Django 5.2.7 on 2025-11-26 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Gallery image from previous events', upload_to='event_gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='events.event')),
            ],
            options={
                'verbose_name_plural': 'Event Gallery Images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
