# Generated by Django 5.2.7 on 2025-11-27 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_paymenttransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
    ]
