# Generated by Django 3.0.7 on 2025-12-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='crowd_image',
            field=models.ImageField(blank=True, help_text='Amazing crowd - Join hundreds of attendees', null=True, upload_to='event_images/crowd/'),
        ),
        migrations.AddField(
            model_name='event',
            name='experience_image',
            field=models.ImageField(blank=True, help_text='Premium experience showcase', null=True, upload_to='event_images/experience/'),
        ),
        migrations.AddField(
            model_name='event',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Main event poster/banner image', null=True, upload_to='event_images/main/'),
        ),
        migrations.AddField(
            model_name='event',
            name='performance_image',
            field=models.ImageField(blank=True, help_text='Live performances and entertainment', null=True, upload_to='event_images/performance/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Legacy image field (use main_image instead)', null=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='eventgallery',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventvideo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
