# Generated by Django 3.0.7 on 2025-12-04 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20251202_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventgallery',
            options={'ordering': ['order', 'id'], 'verbose_name_plural': 'Event Gallery'},
        ),
        migrations.AddField(
            model_name='eventgallery',
            name='is_live_performance',
            field=models.BooleanField(default=False, help_text='Mark as live performance video (for music events)'),
        ),
        migrations.AddField(
            model_name='eventgallery',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='eventgallery',
            name='video_thumbnail',
            field=models.ImageField(blank=True, help_text='Custom thumbnail for video (optional)', null=True, upload_to='event_gallery/video_thumbnails/'),
        ),
        migrations.AddField(
            model_name='eventgallery',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo, or direct video URL for live performances', null=True),
        ),
        migrations.AlterField(
            model_name='eventgallery',
            name='caption',
            field=models.CharField(blank=True, help_text='Optional caption for the media', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventgallery',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='eventgallery',
            name='image',
            field=models.ImageField(blank=True, help_text='Gallery image from previous events', null=True, upload_to='event_gallery/images/'),
        ),
    ]
