# Generated by Django 3.0.7 on 2025-12-07 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_auto_20251204_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text="User's phone number", max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.RemoveField(
            model_name='eventgallery',
            name='is_live_performance',
        ),
        migrations.RemoveField(
            model_name='eventgallery',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='eventgallery',
            name='video_thumbnail',
        ),
        migrations.RemoveField(
            model_name='eventgallery',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='eventgallery',
            name='caption',
            field=models.CharField(blank=True, help_text='Optional caption for the image', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventgallery',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, help_text='Gallery image from previous events', upload_to='event_gallery/images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EventVideo',
        ),
    ]
