# Generated by Django 3.0.7 on 2025-12-15 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20251207_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Resource name', max_length=200)),
                ('resource_type', models.CharField(choices=[('sound', 'Sound System'), ('lighting', 'Lighting Equipment'), ('stage', 'Stage/Platform'), ('seating', 'Additional Seating'), ('security', 'Security Personnel'), ('catering', 'Catering Equipment'), ('transport', 'Transportation'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('cost_per_day', models.DecimalField(decimal_places=2, help_text='Cost per day in Kwacha', max_digits=10)),
                ('quantity_available', models.IntegerField(default=1, help_text='How many units available')),
                ('supplier_name', models.CharField(blank=True, max_length=100)),
                ('supplier_phone', models.CharField(blank=True, max_length=20)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['resource_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Venue name (e.g., Heroes Stadium)', max_length=200)),
                ('address', models.TextField(help_text='Full address of the venue')),
                ('capacity', models.IntegerField(help_text='Maximum capacity')),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Cost per hour in Kwacha', max_digits=10)),
                ('facilities', models.TextField(blank=True, help_text='Available facilities (parking, sound system, etc.)')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VenueBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(help_text='Event start date and time')),
                ('end_datetime', models.DateTimeField(help_text='Event end date and time')),
                ('setup_hours', models.IntegerField(default=2, help_text='Hours needed for setup before event')),
                ('cleanup_hours', models.IntegerField(default=1, help_text='Hours needed for cleanup after event')),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Special requirements or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venue_booking', to='events.Event')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.Venue')),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ResourceAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.IntegerField(default=1, help_text='How many units needed')),
                ('start_date', models.DateField(help_text='When resource is needed from')),
                ('end_date', models.DateField(help_text='When resource is needed until')),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to='events.Event')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='events.Resource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
